isConnected should be set on response closed and prevent pushing data
MatthewWid/better-sse pull request #57
Opened 2024-01-30 14:59 UTC by agix

Response can also close without request emitting the close event.

both should be listened to set the `isConnected` boolean to false.

Also, pushing data should throw on a disconnected session.

2024-02-06 04:46 UTC, martuico commented on src/Session.ts
> +		}
Don't think we need this if statement

2024-02-06 07:29 UTC, MatthewWid requested changes
Looks good aside from a few small things that need a fix-up.

Also the added code is unformatted, please run Prettier before committing: `pnpm run format`.

Thanks for contributing!

2024-02-06 07:29 UTC, MatthewWid commented on src/Session.test.ts
> +						res.emit('close')
```suggestion
						res.end();
```

Just makes more sense semantically, here. We want to test pushing after the session _and_ the underlying connection has closed (which they always should be in tandem.)

2024-02-06 07:33 UTC, MatthewWid commented
Benchmarks look fine.

Before:

```
Benchmarking "Push events with channels".
better-sse x 45,644 ops/sec ±4.66% (85 runs sampled)
```

After:

```
Benchmarking "Push events with channels".
better-sse x 45,425.8 ops/sec ±5.66% (82 runs sampled)
```

2024-02-06 08:33 UTC, agix commented
Thx for the review !

2024-02-08 02:05 UTC, MatthewWid approved these changes
Thanks for the fixes - looks good

2024-02-08 02:05 UTC, merged

2024-02-08 03:09 UTC, MatthewWid commented
These changes are now published in [v0.11.0](https://github.com/MatthewWid/better-sse/releases/tag/v0.11.0).